import { PRODUCT_CATEGORIES, STOCK_CATEGORIES } from './enums';

export const STOCK_ORDER = {
  [STOCK_CATEGORIES.FRESH]: 0,
  [STOCK_CATEGORIES.SMALL_FREEZER]: 1,
  [STOCK_CATEGORIES.LARGE_FREEZER]: 2,
  [STOCK_CATEGORIES.PASTEURIZED_FOR_MARKET]: 3,
  [STOCK_CATEGORIES.PASTEURIZED]: 4,
};

export const CATEGORIES_MATCHING = {
  [PRODUCT_CATEGORIES.FRESH]: [STOCK_CATEGORIES.FRESH],
  [PRODUCT_CATEGORIES.FROZEN]: [STOCK_CATEGORIES.SMALL_FREEZER, STOCK_CATEGORIES.LARGE_FREEZER],
  [PRODUCT_CATEGORIES.PASTEURIZED]: [
    STOCK_CATEGORIES.PASTEURIZED_FOR_MARKET,
    STOCK_CATEGORIES.PASTEURIZED,
  ],
};

/**
 * Returns the stock to update when in market preparation a product's quantity is updated.
 */
export const linkedStockToUpdate = (sc: STOCK_CATEGORIES) => {
  switch (sc) {
    case STOCK_CATEGORIES.PASTEURIZED_FOR_MARKET:
      return STOCK_CATEGORIES.PASTEURIZED;
    case STOCK_CATEGORIES.SMALL_FREEZER:
      return STOCK_CATEGORIES.LARGE_FREEZER;
    default:
      return null;
  }
};
