import { PRODUCT_CATEGORIES, STOCK_CATEGORIES } from './enums';

export const STOCK_ORDER = {
  [STOCK_CATEGORIES.FRESH]: 0,
  [STOCK_CATEGORIES.SMALL_FREEZER]: 1,
  [STOCK_CATEGORIES.LARGE_FREEZER]: 2,
  [STOCK_CATEGORIES.PASTEURIZED]: 3,
};

export const CATEGORIES_MATCHING = {
  [PRODUCT_CATEGORIES.FRESH]: [STOCK_CATEGORIES.FRESH],
  [PRODUCT_CATEGORIES.FROZEN]: [STOCK_CATEGORIES.SMALL_FREEZER, STOCK_CATEGORIES.LARGE_FREEZER],
  [PRODUCT_CATEGORIES.PASTEURIZED]: [STOCK_CATEGORIES.PASTEURIZED],
};
